"""empty message

Revision ID: 1c6943916537
Revises: 
Create Date: 2016-12-14 12:08:03.278416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c6943916537'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('url',
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('key', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('url'),
    sa.UniqueConstraint('key')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('url')
    # ### end Alembic commands ###
